spring:
  ai:
    mcp:
      server:
        enable: true
        name: selenium-automation-mcp
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages
        base-url: /api